import { CompanyDetail, CompanyListItem } from './types'

export const FALLBACK_COMPANIES: CompanyDetail[] = [
  {
    id: 'c-openai',
    name: 'OpenAI',
    slug: 'openai',
    shortDescription: 'Leading AI research and deployment company behind GPT-4 and ChatGPT.',
    description:
      'OpenAI is an AI research and deployment company dedicated to ensuring that artificial general intelligence benefits all of humanity. Known for pioneering foundational language models, multimodal systems, and ChatGPT.',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400',
    website: 'https://openai.com',
    headquarters: 'San Francisco, CA',
    foundedYear: 2015,
    industry: 'Artificial Intelligence',
    companyType: 'RESEARCH',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [
      {
        id: 'p-chatgpt',
        name: 'ChatGPT',
        slug: 'chatgpt',
        description: 'Conversational agent powered by state-of-the-art GPT models.',
        website: 'https://chatgpt.com',
        logo: null,
        createdAt: '2023-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z',
      },
      {
        id: 'p-gpt4o',
        name: 'GPT-4o',
        slug: 'gpt-4o',
        description: 'Omni foundational model reasoning across audio, vision, and text in real time.',
        website: 'https://openai.com/gpt-4o',
        logo: null,
        createdAt: '2024-05-01T00:00:00.000Z',
        updatedAt: '2024-05-01T00:00:00.000Z',
      },
    ],
    categories: [
      { id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: 'Foundation models' },
      { id: 'cat-res', name: 'AI Research', slug: 'ai-research', description: 'Frontier research labs' },
    ],
    relatedCompanies: [
      {
        id: 'c-anthropic',
        name: 'Anthropic',
        slug: 'anthropic',
        shortDescription: 'AI safety and research company building reliable, steerable AI systems like Claude.',
        logo: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
        industry: 'AI Safety',
        companyType: 'STARTUP',
        headquarters: 'San Francisco, CA',
      },
      {
        id: 'c-deepmind',
        name: 'Google DeepMind',
        slug: 'google-deepmind',
        shortDescription: 'World-leading AI research laboratory behind AlphaGo, AlphaFold, and Gemini.',
        logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=400',
        industry: 'AI Research',
        companyType: 'ENTERPRISE',
        headquarters: 'London, UK',
      },
    ],
  },
  {
    id: 'c-anthropic',
    name: 'Anthropic',
    slug: 'anthropic',
    shortDescription: 'AI safety and research company building reliable, steerable AI systems like Claude.',
    description:
      'Anthropic is an AI safety startup focused on building reliable, interpretable, and steerable AI systems. The company develops Claude, an AI assistant built on Constitutional AI principles.',
    logo: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    website: 'https://anthropic.com',
    headquarters: 'San Francisco, CA',
    foundedYear: 2021,
    industry: 'AI Safety',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-02T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [
      {
        id: 'p-claude',
        name: 'Claude 3.5 Sonnet',
        slug: 'claude-3-5-sonnet',
        description: 'Industry-leading intelligence across coding, reasoning, and visual analysis.',
        website: 'https://claude.ai',
        logo: null,
        createdAt: '2024-06-01T00:00:00.000Z',
        updatedAt: '2024-06-01T00:00:00.000Z',
      },
    ],
    categories: [
      { id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: null },
      { id: 'cat-safe', name: 'AI Safety', slug: 'ai-safety', description: null },
    ],
    relatedCompanies: [
      {
        id: 'c-openai',
        name: 'OpenAI',
        slug: 'openai',
        shortDescription: 'Leading AI research and deployment company behind GPT-4 and ChatGPT.',
        logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400',
        industry: 'Artificial Intelligence',
        companyType: 'RESEARCH',
        headquarters: 'San Francisco, CA',
      },
      {
        id: 'c-mistral',
        name: 'Mistral AI',
        slug: 'mistral-ai',
        shortDescription: 'European AI company building open-weight and high-efficiency language models.',
        logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
        industry: 'Large Language Models',
        companyType: 'STARTUP',
        headquarters: 'Paris, France',
      },
    ],
  },
  {
    id: 'c-deepmind',
    name: 'Google DeepMind',
    slug: 'google-deepmind',
    shortDescription: 'World-leading AI research laboratory behind AlphaGo, AlphaFold, and Gemini.',
    description:
      'Google DeepMind combines world-class scientists and engineers to tackle some of humanity’s hardest technical challenges. Known for Gemini models, AlphaFold protein folding, and frontier neural architectures.',
    logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=400',
    website: 'https://deepmind.google',
    headquarters: 'London, UK',
    foundedYear: 2010,
    industry: 'AI Research',
    companyType: 'ENTERPRISE',
    employeeRange: 'ENTERPRISE_501_PLUS',
    status: 'ACTIVE',
    createdAt: '2023-01-03T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [
      {
        id: 'p-gemini',
        name: 'Gemini 1.5 Pro',
        slug: 'gemini-1-5-pro',
        description: 'Multimodal model with a 2-million token context window.',
        website: 'https://gemini.google.com',
        logo: null,
        createdAt: '2024-02-01T00:00:00.000Z',
        updatedAt: '2024-02-01T00:00:00.000Z',
      },
    ],
    categories: [
      { id: 'cat-res', name: 'AI Research', slug: 'ai-research', description: null },
      { id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: null },
    ],
    relatedCompanies: [
      {
        id: 'c-openai',
        name: 'OpenAI',
        slug: 'openai',
        shortDescription: 'Leading AI research and deployment company behind GPT-4 and ChatGPT.',
        logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400',
        industry: 'Artificial Intelligence',
        companyType: 'RESEARCH',
        headquarters: 'San Francisco, CA',
      },
    ],
  },
  {
    id: 'c-mistral',
    name: 'Mistral AI',
    slug: 'mistral-ai',
    shortDescription: 'European AI company building open-weight and high-efficiency language models.',
    description:
      'Mistral AI specializes in open-weights and enterprise models, emphasizing compute efficiency, latency, and open developer access.',
    logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    website: 'https://mistral.ai',
    headquarters: 'Paris, France',
    foundedYear: 2023,
    industry: 'Large Language Models',
    companyType: 'STARTUP',
    employeeRange: 'MEDIUM_11_50',
    status: 'ACTIVE',
    createdAt: '2023-01-04T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [
      {
        id: 'p-mistral-large',
        name: 'Mistral Large 2',
        slug: 'mistral-large-2',
        description: 'Advanced reasoning and code generation model with multilingual fluency.',
        website: 'https://mistral.ai',
        logo: null,
        createdAt: '2024-07-01T00:00:00.000Z',
        updatedAt: '2024-07-01T00:00:00.000Z',
      },
    ],
    categories: [{ id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: null }],
    relatedCompanies: [
      {
        id: 'c-anthropic',
        name: 'Anthropic',
        slug: 'anthropic',
        shortDescription: 'AI safety and research company building reliable, steerable AI systems.',
        logo: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
        industry: 'AI Safety',
        companyType: 'STARTUP',
        headquarters: 'San Francisco, CA',
      },
    ],
  },
  {
    id: 'c-huggingface',
    name: 'Hugging Face',
    slug: 'hugging-face',
    shortDescription: 'The collaborative hub and platform for the global machine learning community.',
    description:
      'Hugging Face is the central platform for sharing, discovering, and evaluating open machine learning models, datasets, and spaces.',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400',
    website: 'https://huggingface.co',
    headquarters: 'New York, NY',
    foundedYear: 2016,
    industry: 'AI Infrastructure',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-05T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [
      {
        id: 'p-hf-hub',
        name: 'Hugging Face Hub',
        slug: 'hugging-face-hub',
        description: 'Git-based repository platform hosting over 500k open models and datasets.',
        website: 'https://huggingface.co/models',
        logo: null,
        createdAt: '2023-01-01T00:00:00.000Z',
        updatedAt: '2024-01-01T00:00:00.000Z',
      },
    ],
    categories: [{ id: 'cat-infra', name: 'AI Infrastructure', slug: 'ai-infrastructure', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-cohere',
    name: 'Cohere',
    slug: 'cohere',
    shortDescription: 'Enterprise AI platform offering high-security foundation models and semantic search.',
    description:
      'Cohere provides enterprise-grade NLP and LLM APIs for semantic search, enterprise search (Command R+), and customer experience workflows.',
    logo: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
    website: 'https://cohere.com',
    headquarters: 'Toronto, Canada',
    foundedYear: 2019,
    industry: 'Enterprise AI',
    companyType: 'STARTUP',
    employeeRange: 'XLARGE_201_500',
    status: 'ACTIVE',
    createdAt: '2023-01-06T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-ent', name: 'Enterprise AI', slug: 'enterprise-ai', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-stability',
    name: 'Stability AI',
    slug: 'stability-ai',
    shortDescription: 'Open-source generative AI company behind Stable Diffusion and Stable Audio.',
    description:
      'Stability AI produces open-source foundation models for imaging, audio, video, and 3D generation.',
    logo: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    website: 'https://stability.ai',
    headquarters: 'London, UK',
    foundedYear: 2020,
    industry: 'Generative AI',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-07T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-gen', name: 'Generative AI', slug: 'generative-ai', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-midjourney',
    name: 'Midjourney',
    slug: 'midjourney',
    shortDescription: 'Independent research lab producing high-aesthetic image generation systems.',
    description:
      'Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species through generative imaging.',
    logo: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=400',
    website: 'https://midjourney.com',
    headquarters: 'San Francisco, CA',
    foundedYear: 2021,
    industry: 'Generative AI',
    companyType: 'STARTUP',
    employeeRange: 'SMALL_2_10',
    status: 'ACTIVE',
    createdAt: '2023-01-08T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-gen', name: 'Generative AI', slug: 'generative-ai', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-scale',
    name: 'Scale AI',
    slug: 'scale-ai',
    shortDescription: 'Data engine and RLHF platform powering frontier AI training pipelines.',
    description:
      'Scale AI provides high-quality data labeling, RLHF, and evaluation platforms for foundation models and enterprise AI applications.',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    website: 'https://scale.com',
    headquarters: 'San Francisco, CA',
    foundedYear: 2016,
    industry: 'AI Infrastructure',
    companyType: 'STARTUP',
    employeeRange: 'ENTERPRISE_501_PLUS',
    status: 'ACTIVE',
    createdAt: '2023-01-09T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-infra', name: 'AI Infrastructure', slug: 'ai-infrastructure', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-replicate',
    name: 'Replicate',
    slug: 'replicate',
    shortDescription: 'Developer platform to run and fine-tune open-source AI models via a single API.',
    description:
      'Replicate lets developers run machine learning models with a cloud API, without having to manage GPU infrastructure or CUDA drivers.',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    website: 'https://replicate.com',
    headquarters: 'San Francisco, CA',
    foundedYear: 2019,
    industry: 'Developer Tools',
    companyType: 'STARTUP',
    employeeRange: 'SMALL_2_10',
    status: 'ACTIVE',
    createdAt: '2023-01-10T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-infra', name: 'AI Infrastructure', slug: 'ai-infrastructure', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-runway',
    name: 'Runway',
    slug: 'runway',
    shortDescription: 'AI research and creative video generation platform behind Gen-2 and Gen-3 Alpha.',
    description:
      'Runway is an applied AI research company building next-generation creative tools for cinema, video production, and world models.',
    logo: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400',
    website: 'https://runwayml.com',
    headquarters: 'New York, NY',
    foundedYear: 2018,
    industry: 'Generative AI',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-11T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-gen', name: 'Generative AI', slug: 'generative-ai', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-perplexity',
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    shortDescription: 'Conversational answer engine delivering real-time cited web research.',
    description:
      'Perplexity AI is a conversational answer engine designed to bring transparent, source-cited intelligence to online search and research.',
    logo: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400',
    website: 'https://perplexity.ai',
    headquarters: 'San Francisco, CA',
    foundedYear: 2022,
    industry: 'Artificial Intelligence',
    companyType: 'STARTUP',
    employeeRange: 'MEDIUM_11_50',
    status: 'ACTIVE',
    createdAt: '2023-01-12T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-elevenlabs',
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    shortDescription: 'Pioneering voice AI research and realistic speech synthesis platform.',
    description:
      'ElevenLabs develops industry-leading generative voice synthesis, speech-to-speech conversion, and real-time conversational voice agents.',
    logo: 'https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=400',
    website: 'https://elevenlabs.io',
    headquarters: 'New York, NY',
    foundedYear: 2022,
    industry: 'Generative AI',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-13T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-gen', name: 'Generative AI', slug: 'generative-ai', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-characterai',
    name: 'Character.AI',
    slug: 'character-ai',
    shortDescription: 'Full-stack conversational agent platform with personalized character interaction.',
    description:
      'Character.AI builds neural language models that allow users to interact with customizable, personality-driven AI agents.',
    logo: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=400',
    website: 'https://character.ai',
    headquarters: 'Menlo Park, CA',
    foundedYear: 2021,
    industry: 'Artificial Intelligence',
    companyType: 'STARTUP',
    employeeRange: 'LARGE_51_200',
    status: 'ACTIVE',
    createdAt: '2023-01-14T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [{ id: 'cat-llm', name: 'Large Language Models', slug: 'large-language-models', description: null }],
    relatedCompanies: [],
  },
  {
    id: 'c-inflection',
    name: 'Inflection AI',
    slug: 'inflection-ai',
    shortDescription: 'AI studio developer of Pi, the supportive personal intelligence companion.',
    description:
      'Inflection AI focused on creating personal, conversational AI designed for everyday human interaction and emotional intelligence.',
    logo: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=400',
    website: 'https://inflection.ai',
    headquarters: 'Palo Alto, CA',
    foundedYear: 2022,
    industry: 'Artificial Intelligence',
    companyType: 'STARTUP',
    employeeRange: 'MEDIUM_11_50',
    status: 'ACQUIRED',
    createdAt: '2023-01-15T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [],
    relatedCompanies: [],
  },
  {
    id: 'c-adept',
    name: 'Adept',
    slug: 'adept',
    shortDescription: 'Building machine learning models that can use software and execute digital actions.',
    description:
      'Adept trained foundation models designed to operate existing enterprise software tools, browsers, and applications on behalf of humans.',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400',
    website: 'https://adept.ai',
    headquarters: 'San Francisco, CA',
    foundedYear: 2022,
    industry: 'Artificial Intelligence',
    companyType: 'STARTUP',
    employeeRange: 'MEDIUM_11_50',
    status: 'ACQUIRED',
    createdAt: '2023-01-16T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    products: [],
    categories: [],
    relatedCompanies: [],
  },
]
